POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhdXMiLCJpZCI6IjYxY2VjMjE2MWM2ODQ0MjFmOWM5MGE1NyIsImlhdCI6MTY0MDk0MDEwNSwiZXhwIjoxNjQwOTQzNzA1fQ.Wx5hPloSaqIU1N9Xw9C0EuE-jH54tvHACfq28Ix_eQc

{
    "title": "I know it all",
    "author": "Asian Tuntija",
    "url": "wwww.theeblogtest.com",
    "likes": "666",
    "userId": "61cec2161c684421f9c90a57"
}
